import type { Employee, Workflow, Ticket, Flow, Role } from '@/types'

export const mockEmployees: Employee[] = [
  {
    email: 'jane.smith@company.com',
    name: 'Jane Smith',
    role: 'engineering',
    start_date: '2026-02-15',
    status: 'onboarded',
    manager: 'sarah@company.com',
    configured_by: 'hr@company.com',
    add_groups: ['vercel-deployers'],
    remove_groups: [],
    resolved_groups: ['engineering-team', 'github-users', 'aws-developers', 'slack-users', 'notion-users', '1password-users', 'vercel-deployers'],
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-15T10:34:00Z',
  },
  {
    email: 'bob.johnson@company.com',
    name: 'Bob Johnson',
    role: 'gtm',
    start_date: '2026-03-13',
    status: 'onboarding',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: ['salesforce-users'],
    remove_groups: ['notion-users'],
    resolved_groups: ['gtm-team', 'slack-users', 'hubspot-users', '1password-users', 'atlassian-users', 'salesforce-users'],
    created_at: '2026-03-10T14:00:00Z',
    updated_at: '2026-03-13T14:16:00Z',
  },
  {
    email: 'alice.chen@company.com',
    name: 'Alice Chen',
    role: 'engineering',
    start_date: '2026-03-01',
    status: 'failed',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['engineering-team', 'github-users', 'aws-developers', 'slack-users', 'notion-users', '1password-users'],
    created_at: '2026-02-25T09:00:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    email: 'dave.kim@company.com',
    name: 'Dave Kim',
    role: 'design',
    start_date: '2026-03-20',
    status: 'pending',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['design-team', 'slack-users', 'notion-users', '1password-users', 'figma-users'],
    created_at: '2026-03-14T16:00:00Z',
    updated_at: '2026-03-14T16:00:00Z',
  },
  {
    email: 'eve.martinez@company.com',
    name: 'Eve Martinez',
    role: 'exec',
    start_date: '2026-03-15',
    status: 'onboarding',
    manager: 'ceo@company.com',
    configured_by: 'hr@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['exec-team', 'slack-users', 'notion-users', '1password-users', 'google-workspace'],
    created_at: '2026-03-12T08:00:00Z',
    updated_at: '2026-03-15T09:30:00Z',
  },
  {
    email: 'tom.wilson@company.com',
    name: 'Tom Wilson',
    role: 'gtm',
    start_date: '2026-02-01',
    status: 'offboarding',
    manager: 'vp-sales@company.com',
    configured_by: 'hr@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: [],
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-03-11T15:00:00Z',
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: 'wf-001',
    employee_email: 'jane.smith@company.com',
    employee_name: 'Jane Smith',
    flow_name: 'engineering_onboard',
    status: 'completed',
    total_domains: 14,
    completed_domains: 14,
    domain_states: {
      okta: { domain: 'okta', status: 'completed', actions: ['create_user', 'assign_groups'], duration_ms: 800 },
      google_workspace: { domain: 'google_workspace', status: 'completed', actions: ['create_account', 'add_to_groups'], duration_ms: 1200 },
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user', 'add_to_channels'], duration_ms: 600 },
      github: { domain: 'github', status: 'completed', actions: ['invite_to_org', 'add_to_teams'], duration_ms: 2100 },
    },
    events: [
      { id: 'e1', event_type: 'flow_started', details: 'engineering_onboard', created_at: '2026-02-15T10:32:01Z' },
      { id: 'e2', event_type: 'phase_completed', details: 'Phase 1: Identity', created_at: '2026-02-15T10:32:02Z' },
      { id: 'e3', event_type: 'phase_completed', details: 'Phase 2: Collaboration', created_at: '2026-02-15T10:32:04Z' },
      { id: 'e4', event_type: 'flow_completed', details: 'All 14 domains provisioned', created_at: '2026-02-15T10:34:00Z' },
    ],
    created_at: '2026-02-15T10:32:00Z',
    updated_at: '2026-02-15T10:34:00Z',
  },
  {
    id: 'wf-002',
    employee_email: 'bob.johnson@company.com',
    employee_name: 'Bob Johnson',
    flow_name: 'gtm_onboard',
    status: 'in_progress',
    total_domains: 10,
    completed_domains: 6,
    domain_states: {
      okta: { domain: 'okta', status: 'completed', actions: ['create_user', 'assign_groups'], duration_ms: 750 },
      google_workspace: { domain: 'google_workspace', status: 'completed', actions: ['create_account'], duration_ms: 1100 },
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user'], duration_ms: 500 },
      notion: { domain: 'notion', status: 'completed', actions: ['add_to_workspace'], duration_ms: 900 },
      atlassian: { domain: 'atlassian', status: 'completed', actions: ['create_user'], duration_ms: 1100 },
      '1password': { domain: '1password', status: 'completed', actions: ['invite_user'], duration_ms: 450 },
      hubspot: { domain: 'hubspot', status: 'pending', actions: [], },
      aws: { domain: 'aws', status: 'pending_approval', actions: [], },
    },
    events: [
      { id: 'e5', event_type: 'flow_started', details: 'gtm_onboard', created_at: '2026-03-13T14:15:00Z' },
      { id: 'e6', event_type: 'phase_completed', details: 'Phase 1: Identity', created_at: '2026-03-13T14:15:02Z' },
      { id: 'e7', event_type: 'approval_requested', details: 'AWS admin access requires approval', created_at: '2026-03-13T14:15:03Z' },
    ],
    created_at: '2026-03-13T14:15:00Z',
    updated_at: '2026-03-13T14:16:00Z',
  },
  {
    id: 'wf-003',
    employee_email: 'alice.chen@company.com',
    employee_name: 'Alice Chen',
    flow_name: 'engineering_offboard',
    status: 'failed',
    total_domains: 14,
    completed_domains: 3,
    domain_states: {
      okta: { domain: 'okta', status: 'completed', actions: ['deactivate_user'], duration_ms: 600 },
      google_workspace: { domain: 'google_workspace', status: 'completed', actions: ['suspend_account'], duration_ms: 800 },
      slack: { domain: 'slack', status: 'completed', actions: ['deactivate_user'], duration_ms: 400 },
      github: { domain: 'github', status: 'failed', actions: ['remove_from_org'], error: 'GitHub API rate limit exceeded. Retry after 60s.' },
    },
    events: [
      { id: 'e8', event_type: 'flow_started', details: 'engineering_offboard', created_at: '2026-03-13T11:20:00Z' },
      { id: 'e9', event_type: 'domain_failed', details: 'GitHub: rate limit exceeded', created_at: '2026-03-13T11:22:00Z' },
    ],
    created_at: '2026-03-13T11:20:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    id: 'wf-004',
    employee_email: 'dave.kim@company.com',
    employee_name: 'Dave Kim',
    flow_name: 'design_onboard',
    status: 'pending',
    total_domains: 8,
    completed_domains: 0,
    domain_states: {},
    events: [],
    created_at: '2026-03-14T16:00:00Z',
    updated_at: '2026-03-14T16:00:00Z',
  },
  {
    id: 'wf-005',
    employee_email: 'eve.martinez@company.com',
    employee_name: 'Eve Martinez',
    flow_name: 'exec_onboard',
    status: 'in_progress',
    total_domains: 7,
    completed_domains: 6,
    domain_states: {
      okta: { domain: 'okta', status: 'completed', actions: ['create_user'], duration_ms: 700 },
      google_workspace: { domain: 'google_workspace', status: 'completed', actions: ['create_account'], duration_ms: 1000 },
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user'], duration_ms: 550 },
      notion: { domain: 'notion', status: 'completed', actions: ['add_to_workspace'], duration_ms: 800 },
      '1password': { domain: '1password', status: 'completed', actions: ['invite_user'], duration_ms: 400 },
      atlassian: { domain: 'atlassian', status: 'completed', actions: ['create_user'], duration_ms: 950 },
      hubspot: { domain: 'hubspot', status: 'pending', actions: [] },
    },
    events: [],
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-15T09:30:00Z',
  },
  {
    id: 'wf-006',
    employee_email: 'tom.wilson@company.com',
    employee_name: 'Tom Wilson',
    flow_name: 'gtm_offboard',
    status: 'completed',
    total_domains: 10,
    completed_domains: 10,
    domain_states: {},
    events: [],
    created_at: '2026-03-11T14:00:00Z',
    updated_at: '2026-03-11T15:00:00Z',
  },
]

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-042',
    type: 'approval',
    title: 'AWS Admin access for bob.johnson@company.com',
    description: 'Bob Johnson requires AWS admin access as part of GTM onboarding. This action is approval-gated per execution policy.',
    status: 'open',
    workflow_id: 'wf-002',
    employee_email: 'bob.johnson@company.com',
    domain: 'aws',
    action: 'grant_admin_access',
    approvers: [
      { email: 'sarah@company.com', status: 'pending' },
      { email: 'it-admin@company.com', status: 'pending' },
    ],
    assignee: 'sarah@company.com',
    created_at: '2026-03-13T14:15:03Z',
    updated_at: '2026-03-13T14:15:03Z',
    expires_at: '2026-03-17T14:15:03Z',
  },
  {
    id: 'TKT-041',
    type: 'failure',
    title: 'GitHub invite failed for alice.chen@company.com',
    description: 'GitHub API returned rate limit error during engineering offboarding. The remove_from_org action could not be completed.',
    status: 'open',
    workflow_id: 'wf-003',
    employee_email: 'alice.chen@company.com',
    domain: 'github',
    action: 'remove_from_org',
    approvers: [],
    assignee: 'it-admin@company.com',
    created_at: '2026-03-13T11:22:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    id: 'TKT-040',
    type: 'manual_config',
    title: 'Configure Figma seat for dave.kim@company.com',
    description: 'Figma requires manual seat assignment. Please add dave.kim@company.com to the Design team workspace.',
    status: 'open',
    workflow_id: 'wf-004',
    employee_email: 'dave.kim@company.com',
    domain: 'figma',
    action: 'assign_seat',
    approvers: [],
    assignee: 'it-admin@company.com',
    created_at: '2026-03-14T16:01:00Z',
    updated_at: '2026-03-14T16:01:00Z',
  },
  {
    id: 'TKT-039',
    type: 'approval',
    title: 'Datadog admin access for jane.smith@company.com',
    description: 'Jane Smith requested Datadog admin access upgrade.',
    status: 'resolved',
    workflow_id: 'wf-001',
    employee_email: 'jane.smith@company.com',
    domain: 'datadog',
    action: 'grant_admin',
    approvers: [
      { email: 'sarah@company.com', status: 'approved' },
      { email: 'it-admin@company.com', status: 'approved' },
    ],
    assignee: 'sarah@company.com',
    resolution: 'Approved by both approvers',
    created_at: '2026-02-15T10:33:00Z',
    updated_at: '2026-02-15T11:00:00Z',
  },
  {
    id: 'TKT-038',
    type: 'info',
    title: 'Onboarding summary for eve.martinez@company.com',
    description: 'Executive onboarding in progress. 6 of 7 domains provisioned. Waiting on HubSpot.',
    status: 'open',
    workflow_id: 'wf-005',
    employee_email: 'eve.martinez@company.com',
    approvers: [],
    created_at: '2026-03-15T09:30:00Z',
    updated_at: '2026-03-15T09:30:00Z',
  },
]

export const mockFlows: Flow[] = [
  {
    name: 'engineering_onboard',
    display_name: 'Engineering Onboard',
    action: 'onboard',
    role: 'engineering',
    total_domains: 14,
    phases: [
      { name: 'Identity', domains: ['okta'] },
      { name: 'Collaboration', domains: ['google_workspace', 'slack', 'notion', 'atlassian', '1password'] },
      { name: 'Engineering Tools', domains: ['github', 'linear'] },
      { name: 'DevOps', domains: ['vercel', 'datadog', 'cloudflare'] },
      { name: 'Infrastructure', domains: ['aws', 'mongodb'] },
    ],
  },
  {
    name: 'gtm_onboard',
    display_name: 'GTM Onboard',
    action: 'onboard',
    role: 'gtm',
    total_domains: 10,
    phases: [
      { name: 'Identity', domains: ['okta'] },
      { name: 'Collaboration', domains: ['google_workspace', 'slack', 'notion', 'atlassian', '1password'] },
      { name: 'GTM Tools', domains: ['hubspot'] },
    ],
  },
  {
    name: 'design_onboard',
    display_name: 'Design Onboard',
    action: 'onboard',
    role: 'design',
    total_domains: 8,
    phases: [
      { name: 'Identity', domains: ['okta'] },
      { name: 'Collaboration', domains: ['google_workspace', 'slack', 'notion', 'atlassian', '1password'] },
      { name: 'Design Tools', domains: ['figma'] },
    ],
  },
  {
    name: 'exec_onboard',
    display_name: 'Executive Onboard',
    action: 'onboard',
    role: 'exec',
    total_domains: 7,
    phases: [
      { name: 'Identity', domains: ['okta'] },
      { name: 'Collaboration', domains: ['google_workspace', 'slack', 'notion', '1password', 'atlassian'] },
    ],
  },
]

export const mockRoles: Role[] = [
  {
    name: 'engineering',
    display_name: 'Engineering',
    baseline_groups: ['engineering-team', 'github-users', 'aws-developers', 'slack-users', 'notion-users', '1password-users'],
    approval_required: ['aws-admin', 'datadog-admin'],
  },
  {
    name: 'gtm',
    display_name: 'GTM',
    baseline_groups: ['gtm-team', 'slack-users', 'notion-users', 'hubspot-users', '1password-users', 'atlassian-users'],
    approval_required: ['salesforce-admin'],
  },
  {
    name: 'design',
    display_name: 'Design',
    baseline_groups: ['design-team', 'slack-users', 'notion-users', '1password-users', 'figma-users'],
    approval_required: [],
  },
  {
    name: 'exec',
    display_name: 'Executive',
    baseline_groups: ['exec-team', 'slack-users', 'notion-users', '1password-users', 'google-workspace'],
    approval_required: [],
  },
]
