import type { Employee, Workflow, Ticket, Flow, Role, ToolRequest } from '@/types'

export const mockEmployees: Employee[] = [
  {
    email: 'jane.smith@company.com',
    name: 'Jane Smith',
    role: 'engineering',
    start_date: '2026-02-15',
    status: 'onboarded',
    manager: 'sarah@company.com',
    configured_by: 'hr@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['engineering-team', 'github-member', 'slack-member', 'asana-engineering', 'trello-engineering'],
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-15T10:34:00Z',
  },
  {
    email: 'bob.johnson@company.com',
    name: 'Bob Johnson',
    role: 'gtm',
    start_date: '2026-03-13',
    status: 'onboarding',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['gtm-team', 'slack-member', 'github-member', 'trello-gtm', 'hubspot-sales'],
    created_at: '2026-03-10T14:00:00Z',
    updated_at: '2026-03-13T14:16:00Z',
  },
  {
    email: 'alice.chen@company.com',
    name: 'Alice Chen',
    role: 'engineering',
    start_date: '2026-03-01',
    status: 'failed',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['engineering-team', 'github-member', 'slack-member', 'asana-engineering'],
    created_at: '2026-02-25T09:00:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    email: 'dave.kim@company.com',
    name: 'Dave Kim',
    role: 'design',
    start_date: '2026-03-20',
    status: 'pending',
    manager: 'sarah@company.com',
    configured_by: 'sarah@company.com',
    add_groups: [],
    remove_groups: [],
    resolved_groups: ['design-team', 'slack-member', 'github-member', 'trello-design', 'figma-editor'],
    created_at: '2026-03-14T16:00:00Z',
    updated_at: '2026-03-14T16:00:00Z',
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: 'wf-001',
    employee_email: 'jane.smith@company.com',
    employee_name: 'Jane Smith',
    flow_name: 'engineering_onboard',
    status: 'completed',
    total_domains: 4,
    completed_domains: 4,
    domain_states: {
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user', 'add_to_channels'], duration_ms: 600 },
      github: { domain: 'github', status: 'completed', actions: ['add_org_member', 'add_to_team'], duration_ms: 2100 },
      asana: { domain: 'asana', status: 'completed', actions: ['add_to_project', 'add_to_team'], duration_ms: 900 },
      trello: { domain: 'trello', status: 'completed', actions: ['add_to_board'], duration_ms: 450 },
    },
    events: [
      { id: 'e1', event_type: 'flow_started', details: 'engineering_onboard', created_at: '2026-02-15T10:32:01Z' },
      { id: 'e2', event_type: 'phase_completed', details: 'Phase 1: Collaboration (Slack, GitHub)', created_at: '2026-02-15T10:32:04Z' },
      { id: 'e3', event_type: 'phase_completed', details: 'Phase 2: Project Tools (Asana, Trello)', created_at: '2026-02-15T10:32:06Z' },
      { id: 'e4', event_type: 'flow_completed', details: 'All 4 domains provisioned', created_at: '2026-02-15T10:34:00Z' },
    ],
    created_at: '2026-02-15T10:32:00Z',
    updated_at: '2026-02-15T10:34:00Z',
  },
  {
    id: 'wf-002',
    employee_email: 'bob.johnson@company.com',
    employee_name: 'Bob Johnson',
    flow_name: 'gtm_onboard',
    status: 'in_progress',
    total_domains: 4,
    completed_domains: 3,
    domain_states: {
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user'], duration_ms: 500 },
      github: { domain: 'github', status: 'completed', actions: ['add_org_member'], duration_ms: 1800 },
      trello: { domain: 'trello', status: 'completed', actions: ['add_to_board'], duration_ms: 400 },
      hubspot: { domain: 'hubspot', status: 'pending', actions: [] },
    },
    events: [
      { id: 'e5', event_type: 'flow_started', details: 'gtm_onboard', created_at: '2026-03-13T14:15:00Z' },
      { id: 'e6', event_type: 'phase_completed', details: 'Phase 1: Collaboration', created_at: '2026-03-13T14:15:02Z' },
    ],
    created_at: '2026-03-13T14:15:00Z',
    updated_at: '2026-03-13T14:16:00Z',
  },
  {
    id: 'wf-003',
    employee_email: 'alice.chen@company.com',
    employee_name: 'Alice Chen',
    flow_name: 'engineering_onboard',
    status: 'failed',
    total_domains: 4,
    completed_domains: 3,
    domain_states: {
      slack: { domain: 'slack', status: 'completed', actions: ['invite_user'], duration_ms: 400 },
      github: { domain: 'github', status: 'completed', actions: ['add_org_member'], duration_ms: 1500 },
      asana: { domain: 'asana', status: 'completed', actions: ['add_to_project'], duration_ms: 700 },
      trello: { domain: 'trello', status: 'failed', actions: ['add_to_board'], error: 'Trello API rate limit exceeded. Retry after 60s.' },
    },
    events: [
      { id: 'e8', event_type: 'flow_started', details: 'engineering_onboard', created_at: '2026-03-13T11:20:00Z' },
      { id: 'e9', event_type: 'domain_failed', details: 'Trello: rate limit exceeded', created_at: '2026-03-13T11:22:00Z' },
    ],
    created_at: '2026-03-13T11:20:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    id: 'wf-004',
    employee_email: 'dave.kim@company.com',
    employee_name: 'Dave Kim',
    flow_name: 'design_onboard',
    status: 'pending',
    total_domains: 4,
    completed_domains: 0,
    domain_states: {},
    events: [],
    created_at: '2026-03-14T16:00:00Z',
    updated_at: '2026-03-14T16:00:00Z',
  },
]

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-042',
    type: 'failure',
    title: 'Trello invite failed for alice.chen@company.com',
    description: 'Trello API returned rate limit error during engineering onboarding.',
    status: 'open',
    workflow_id: 'wf-003',
    employee_email: 'alice.chen@company.com',
    domain: 'trello',
    action: 'add_to_board',
    approvers: [],
    assignee: 'it-admin@company.com',
    created_at: '2026-03-13T11:22:00Z',
    updated_at: '2026-03-13T11:22:00Z',
  },
  {
    id: 'TKT-041',
    type: 'manual_config',
    title: 'Configure Figma seat for dave.kim@company.com',
    description: 'Figma requires manual seat assignment. Please add dave.kim@company.com to the Design team workspace.',
    status: 'open',
    workflow_id: 'wf-004',
    employee_email: 'dave.kim@company.com',
    domain: 'figma',
    action: 'assign_seat',
    approvers: [],
    assignee: 'it-admin@company.com',
    created_at: '2026-03-14T16:01:00Z',
    updated_at: '2026-03-14T16:01:00Z',
  },
  {
    id: 'TKT-039',
    type: 'approval',
    title: 'AWS access for jane.smith@company.com',
    description: 'Jane Smith requested AWS staging access.',
    status: 'resolved',
    workflow_id: 'wf-001',
    employee_email: 'jane.smith@company.com',
    domain: 'aws',
    action: 'grant_access',
    approvers: [
      { email: 'sarah@company.com', status: 'approved' },
    ],
    assignee: 'sarah@company.com',
    resolution: 'Approved',
    created_at: '2026-02-15T10:33:00Z',
    updated_at: '2026-02-15T11:00:00Z',
  },
]

export const mockFlows: Flow[] = [
  {
    name: 'engineering_onboard',
    display_name: 'Engineering Onboard',
    action: 'onboard',
    role: 'engineering',
    total_domains: 4,
    phases: [
      { name: 'Collaboration', domains: ['slack', 'github'] },
      { name: 'Project Tools', domains: ['asana', 'trello'] },
    ],
  },
  {
    name: 'gtm_onboard',
    display_name: 'GTM Onboard',
    action: 'onboard',
    role: 'gtm',
    total_domains: 4,
    phases: [
      { name: 'Collaboration', domains: ['slack', 'github'] },
      { name: 'GTM Tools', domains: ['trello', 'hubspot'] },
    ],
  },
  {
    name: 'design_onboard',
    display_name: 'Design Onboard',
    action: 'onboard',
    role: 'design',
    total_domains: 4,
    phases: [
      { name: 'Collaboration', domains: ['slack', 'github'] },
      { name: 'Design Tools', domains: ['trello', 'figma'] },
    ],
  },
  {
    name: 'exec_onboard',
    display_name: 'Executive Onboard',
    action: 'onboard',
    role: 'exec',
    total_domains: 4,
    phases: [
      { name: 'Collaboration', domains: ['slack', 'github'] },
      { name: 'Management', domains: ['asana', 'trello'] },
    ],
  },
]

export const availableTools: { name: string; category: string }[] = [
  { name: 'Cursor', category: 'IDE' },
  { name: 'Claude Code', category: 'IDE' },
  { name: 'VS Code', category: 'IDE' },
  { name: 'JetBrains', category: 'IDE' },
  { name: 'GitHub Copilot', category: 'AI Assistant' },
  { name: 'Claude Pro', category: 'AI Assistant' },
  { name: 'Figma', category: 'Design' },
  { name: 'Asana', category: 'Project Management' },
  { name: 'Trello', category: 'Project Management' },
  { name: 'Slack', category: 'Collaboration' },
  { name: 'Datadog', category: 'Observability' },
  { name: 'AWS', category: 'Infrastructure' },
  { name: 'Vercel', category: 'Infrastructure' },
]

export const mockToolRequests: ToolRequest[] = [
  {
    id: 'tr-001',
    requester: 'sarah@company.com',
    employee_email: 'jane.smith@company.com',
    employee_name: 'Jane Smith',
    tool_from: 'Cursor',
    tool_to: 'Claude Code',
    reason: 'Team is migrating to Claude Code for better agentic workflows',
    status: 'pending',
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
]

export const mockRoles: Role[] = [
  {
    name: 'engineering',
    display_name: 'Engineering',
    baseline_groups: ['slack-member', 'github-member', 'asana-engineering', 'trello-engineering'],
    approval_required: ['aws-staging'],
  },
  {
    name: 'gtm',
    display_name: 'GTM',
    baseline_groups: ['slack-member', 'github-member', 'trello-gtm', 'hubspot-sales'],
    approval_required: [],
  },
  {
    name: 'design',
    display_name: 'Design',
    baseline_groups: ['slack-member', 'github-member', 'trello-design', 'figma-editor'],
    approval_required: [],
  },
  {
    name: 'exec',
    display_name: 'Executive',
    baseline_groups: ['slack-member', 'github-member', 'asana-all-teams', 'trello-leadership'],
    approval_required: [],
  },
]
